### ISSUE TITLE
Bug: Helm Chart `auth.mgmt[].*` not being applied on deploy

### ISSUE THREAD

**Issue by aRustyDev** [aRustyDev/memphis#1]
### Describe the bug

When deploying memphis v1.4.4 via the helm chart, setting the `auth.mgmt` values does not create UI users to login with

### Steps to reproduce

```yaml
auth:
  enabled: true
  users:
   mgmt: # Does not create admin user
   - user: admin
     password: admin
```

### Affected services

Other

### Broker version

v1.4.4

### Platforms

Kubernetes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
